#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

# Environment variables
export NEXUS_NAME=`ls $OPENSHIFT_DATA_DIR | grep nexus-*`
export NEXUS_HOME=$OPENSHIFT_DATA_DIR/$NEXUS_NAME

# Launch the Jetty server directly.
cd $NEXUS_HOME
java -cp lib/*:conf/ \
-Djava.net.preferIPv4Stack=true \
-Dcom.sun.jndi.ldap.connect.pool.protocol="plain ssl" \
org.sonatype.nexus.bootstrap.Launcher \
conf/jetty.xml \
conf/jetty-http-redirect-to-https.xml \
conf/jetty-requestlog.xml \
> $OPENSHIFT_DIY_LOG_DIR/out.log &

echo "Sonatype Nexus will be started"
